Play travis
Otus-DevOps-2021-02/FreeForGor_infra pull request #3
Opened 2021-03-29 08:13 UTC by FreeForGor

2021-03-30 08:25 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Вам стоит свериться с методичкой тесты у вас проходят не полностью, так же добавить описание к вашим пр. ДЗ отправляю на доработку.

2021-03-30 08:25 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Хммм =)

2021-03-31 07:31 UTC, FreeForGor commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Аааааааа
Я все не могу привыкнуть к таким мемам

2021-03-31 11:44 UTC, mrgreyves requested changes
Здравствуйте!) Все еще нет, пока что у вас отрабатывает только auto assign, нужно что бы бежали тесты. Нужно добавить отдельный workflow, ссылка на него есть в методичке. ДЗ возвращаю на доработку.

2021-04-01 07:38 UTC, FreeForGor commented
Тесты побежали

2021-04-02 12:56 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь все хорошо =) Не забывайте добавлять описание к вашим пр =) ДЗ принимаю!=)
![image](https://user-images.githubusercontent.com/34331259/113417394-fef44e80-93cb-11eb-85a4-af1e4c0e1a3d.png)

2021-04-08 09:21 UTC, merged